title: Transcendent Tapir
description: A Queer game development co-operative
sitename: Transcendent Tapir
#baseurl: '/'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME